services:
  legacy_heat_sensor_bridge:
    image: legacy_heat_sensor_bridge:latest
    container_name: legacy_heat_sensor_bridge
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASSWD: ${DB_PASSWD}
      DB_NAME: ${DB_NAME}
    network_mode: host
    restart: unless-stopped
